# File:        .zshenv
# Author:      Zakhary Kaplan <https://zakhary.dev>
# Created:     09 May 2021
# SPDX-License-Identifier: MIT

# The directory to search for shell startup files (.zshrc, etc).
# If ZDOTDIR is unset, HOME is used instead.
ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
