# File:        config.toml
# Author:      Zakhary Kaplan <https://zakhary.dev>
# Created:     11 Feb 2024
# SPDX-License-Identifier: MIT

[install]
root = "."                  # `cargo install` destination directory
