# File:        Brewfile
# Author:      Zakhary Kaplan <https://zakharykaplan.ca>
# Created:     18 Jul 2019
# SPDX-License-Identifier: MIT

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "bash"
brew "bat"
brew "coreutils"
brew "ctags"
brew "fd"
brew "fzf"
brew "htop"
brew "node"
brew "ripgrep"
brew "stow"
brew "tmux"
brew "tree"
brew "vim"
brew "zsh"
